version: '3.9'

services:
    # PHP Service
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: unless-stopped
        environment:
            TIMEZONE: Europe/Prague

    # Nginx Service
    webserver:
        image: nginx:1.25.1
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
